#Docker base image : Alpine Linux with OpenJDK JRE
FROM openjdk:8-jdk-alpine

#Check the java version
RUN ["java", "-version"]


#Install maven
RUN apk update
RUN apk add maven


RUN mkdir -p /opt/todobackend
WORKDIR /opt/todobackend


#Copy the SRC, LIB and pom.xml to WORKDIR
ADD todobackend/pom.xml /opt/todobackend/pom.xml
ADD todobackend/src /opt/todobackend/src

#Build the code
RUN ["mvn", "clean"]
RUN ["mvn", "install", "-DskipTests"]

#Optional you can include commands to run test cases.

#Port the container listens on
EXPOSE 8080

#CMD to be executed when docker is run.
ENV JAVA_ARGS=""
#CMD ["java", "$JAVA_ARGS", "-jar", "todobackend-0.0.1-SNAPSHOT.jar"]
CMD java $JAVA_ARGS -jar todobackend-0.0.1-SNAPSHOT.jar
